### PR TITLE
Add the "scene get" command

### PR DESCRIPTION
**Pull request by twidi**
Having a way to get the current scene allows manipulating it, knowing it's the current one.

PS: it's my first code in go, it works on my computer, I didn't find any tests to add some, but feel three to do whatever you want with this small piece of code :)

### CODE REVIEW

**Comment by muesli** [comment]
Looks good to me, thank you!

**Comment by muesli** [comment]
> PS: it's my first code in go, it works on my computer, I didn't find any tests to add some, but feel three to do whatever you want with this small piece of code :)

Sadly, there aren't any tests currently. We could have integration tests that require a running OBS instance to test against, but that's not exactly easy to set up.

**Comment by twidi** [comment]
> Sadly, there aren't any tests currently. We could have integration tests that require a running OBS instance to test against, but that's not exactly easy to set up.

I totally get it. 

Thanks for you tool, I use it for my streamdeck (on linux, to use with my own streamdeck lib, so I needed command line obs commands)

**Comment by muesli** [comment]
> Thanks for you tool, I use it for my streamdeck (on linux, to use with my own streamdeck lib, so I needed command line obs commands)

`streamdeckfs` looks pretty cool! That's funny, because I also wrote `deckmaster` and a Go library to access Stream Decks:

https://github.com/muesli/deckmaster/
https://github.com/muesli/streamdeck/

**Comment by twidi** [comment]
It's possible that every person using linux wrote its own streamdeck tool.... :D

**Pull request merged**
